module.exports = {
	// possible problems
	"array-callback-return": "error",
	"constructor-super": "error",
	"for-direction": "off",
	"getter-return": "off",
	"no-await-in-loop": "off",
	"no-class-assign": "error",
	"no-compare-neg-zero": "error",
	"no-cond-assign": "error",
	"no-const-assign": "error",
	"no-constant-condition": ["error", {
		checkLoops: false,
	}],
	"no-control-regex": "error",
	"no-debugger": "error",
	"no-dupe-args": "error",
	"no-dupe-class-members": "error",
	"no-dupe-else-if": "error",
	"no-dupe-keys": "error",
	"no-duplicate-case": "error",
	"no-duplicate-imports": "error",
	"no-empty-character-class": "error",
	"no-empty-pattern": "error",
	"no-ex-assign": "error",
	"no-fallthrough": "error",
	"no-func-assign": "error",
	"no-import-assign": "error",
	"no-inner-declarations": ["error", "functions"],
	"no-invalid-regexp": "error",
	"no-irregular-whitespace": "error",
	"no-new-symbol": "error",
	"no-object-constructor": "error",
	"no-obj-calls": "error",
	"no-prototype-builtins": "off",
	"no-self-assign": "error",
	"no-self-compare": "error",
	"no-setter-return": "error",
	"no-sparse-arrays": "error",
	"no-template-curly-in-string": "error",
	"no-this-before-super": "error",
	"no-undef": "error",
	"no-unexpected-multiline": "error",
	"no-unmodified-loop-condition": "error",
	"no-unreachable": "error",
	"no-unsafe-finally": "error",
	"no-unsafe-negation": "error",
	"no-unsafe-optional-chaining": "error",
	"no-unused-vars": ["error", {
		vars: "all",
		args: "none",
		ignoreRestSiblings: true,
	}],
	"no-use-before-define": ["error", {
		functions: false,
		classes: false,
		variables: false,
	}],
	"use-isnan": "error",
	"valid-typeof": ["error", {
		requireStringLiterals: true,
	}],

	// suggestions
	"accessor-pairs": "error",
	"arrow-body-style": ["error", "as-needed"],
	"blocked-scoped-var": "off",
	camelcase: ["error", {
		properties: "never",
	}],
	"class-methods-use-this": "error",
	complexity: "off",
	"consistent-return": "warn",
	curly: ["error", "all"],
	"default-case": "error",
	"default-case-last": "error",
	"default-param-last": "error",
	"dot-notation": "error",
	eqeqeq: ["error", "always"],
	"guard-for-in": "off",
	"init-declarations": "off",
	"new-cap": ["error", {
		newIsCap: true,
		capIsNew: false,
	}],
	"no-alert": "off",
	"no-caller": "error",
	"no-case-declarations": "error",
	"no-console": "warn",
	"no-delete-var": "error",
	"no-div-regex": "off",
	"no-else-return": "error",
	"no-empty": "error",
	"no-empty-function": "error",
	"no-eq-null": "off",
	"no-eval": "error",
	"no-extend-native": "error",
	"no-extra-bind": "error",
	"no-extra-boolean-cast": "error",
	"no-extra-label": "off",
	"no-global-assign": "error",
	"no-implicit-coercion": "error",
	"no-implicit-globals": "error",
	"no-implied-eval": "error",
	"no-invalid-this": "off",
	"no-iterator": "error",
	"no-label-var": "error",
	"no-labels": ["error", {
		allowLoop: false,
		allowSwitch: false,
	}],
	"no-lone-blocks": "error",
	"no-loop-func": "off",
	"no-magic-numbers": "off",
	"no-multi-str": "error",
	"no-nested-ternary": "error",
	"no-new": "error",
	"no-new-func": "error",
	"no-new-wrappers": "error",
	"no-octal": "error",
	"no-octal-escape": "error",
	"no-param-reassign": "off",
	"no-proto": "error",
	"no-redeclare": "error",
	"no-regex-spaces": "error",
	"no-restricted-globals": "off",
	"no-restricted-imports": "off",
	"no-restricted-properties": "off",
	"no-return-assign": ["error", "except-parens"],
	"no-script-url": "off",
	"no-sequences": "error",
	"no-shadow-restricted-names": "error",
	"no-throw-literal": "error",
	"no-undef-init": "error",
	"no-undefined": "off",
	"no-unneeded-ternary": ["error", {
		defaultAssignment: false,
	}],
	"no-unused-expressions": ["error", {
		allowShortCircuit: true,
		allowTernary: true,
		allowTaggedTemplates: true,
	}],
	"no-unused-labels": "off",
	"no-useless-call": "error",
	"no-useless-computed-key": "off",
	"no-useless-concat": "off",
	"no-useless-constructor": "error",
	"no-useless-escape": "error",
	"no-useless-rename": "error",
	"no-useless-return": "error",
	"no-var": "error",
	"no-void": "off",
	"no-warning-comments": "off",
	"no-with": "error",
	"object-shorthand": ["error", "always"],
	"one-var": ["error", {
		initialized: "never",
	}],
	"prefer-arrow-callback": "error",
	"prefer-const": "error",
	"prefer-destructuring": ["error", {
		object: true,
		array: true,
	}],
	"prefer-numeric-literals": "off",
	"prefer-promise-reject-errors": "error",
	"prefer-rest-params": "error",
	"prefer-spread": "warn",
	"prefer-template": "error",
	radix: "off",
	"require-await": "off",
	"require-yield": "error",
	"sort-imports": "off",
	strict: "off",
	"symbol-description": "error",
	"vars-on-top": "off",
	yoda: ["error", "never"],

	// layout & formatting
	"unicode-bom": ["error", "never"],
};
